version: "3.8"

x-uffizzi:
  ingress:
    service: localstack
    port: 4566

services:
  localstack:
    build: 
      context: .
      dockerfile: /Dockerfile
    ports:
      - "4566:4566"            # LocalStack Gateway
    environment:
      - SERVICES=lambda,iam,s3
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=testUser
      - AWS_SECRET_ACCESS_KEY=testAccessKey
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - localstack_data:/var/lib/localstack"
      # - "/var/run/docker.sock:/var/run/docker.sock"
      - ./create-resources.sh:/docker-entrypoint-initaws.d/create-resources.sh
    
volumes:
  localstack_data: