version: "3.8"

x-uffizzi:
  ingress:
    service: nginx
    port: 8081

services:
 
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx-uffizzi:/etc/nginx
  
  localstack:
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "4566:4566"            # LocalStack Gateway
    environment:
      - SERVICES=lambda,iam,s3
      - DEBUG=1
      - DISABLE_CORS_CHECKS=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/tmp/localstack/data
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=testUser
      - AWS_SECRET_ACCESS_KEY=testAccessKey
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - localstack_data:/var/lib/localstack"
      - docker_volume:/var/run/docker.sock
      - ./create-resources.sh:/docker-entrypoint-initaws.d/create-resources.sh
    
volumes:
  localstack_data:
  docker_volume: